//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myStore_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaksi_header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transaksi_header()
        {
            this.transaksi_detail = new HashSet<transaksi_detail>();
        }
    
        public int id_transaksi { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public Nullable<int> id_customer { get; set; }
        public string keterangan { get; set; }
        public Nullable<decimal> total_belanja { get; set; }
        public Nullable<decimal> pajak { get; set; }
        public Nullable<decimal> total_bayar { get; set; }
        public Nullable<decimal> bayar { get; set; }
        public Nullable<decimal> kembalian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaksi_detail> transaksi_detail { get; set; }
    }
}
