//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myStore_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id_user { get; set; }
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string user_pass { get; set; }
        public string user_avatar { get; set; }
        public string user_email { get; set; }
        public Nullable<int> user_level { get; set; }
    }
}
